namespace Algorithms.Code.ProjectEuler
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
    /// By starting with 1 and 2, the first 10 terms will be:
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
    /// find the sum of the even-valued terms.
    /// </summary>
    public class EvenFibonacciNumbers
    {
        public int Sum(int max)
        {
            var n0 = 1;
            var n1 = 2;
            var sum = 0;
            while (n1 <= max)
            {
                if (n1 % 2 == 0)
                {
                    sum += n1;
                }
                var n2 = n1;
                n1 += n0;
                n0 = n2;
            }
            return sum;
        }
    }
}
